/*
 * This source file was generated by the Gradle 'init' task
 */
package SnakeLadder;

import SnakeLadder.Services.GameData;
import SnakeLadder.Services.InitializeGameService;
import SnakeLadder.Services.PlayGameService;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.print("Welcome to Snake and Ladder Game!!\n");
        Scanner sc = new Scanner(System.in);

        System.out.print("Enter number of players: ");
        Integer noOfPlayers = sc.nextInt();

        System.out.print("Enter dice capacity: ");
        Integer diceCapacity = sc.nextInt();

        System.out.print("Enter size of board: ");
        Integer sizeOfBoard = sc.nextInt();

        System.out.print("Enter number of snakes: ");
        Integer noOfSnake = sc.nextInt();

        System.out.print("Enter number of ladders: ");
        Integer noOfLadder = sc.nextInt();

        System.out.println();

        InitializeGameService intializeGameService = new InitializeGameService(noOfPlayers, diceCapacity, sizeOfBoard, noOfSnake, noOfLadder, sc);
        GameData gameData = intializeGameService.initializeGame();
        PlayGameService playGameService = new PlayGameService(gameData);
        playGameService.playGame();
        playGameService.announceWinner();
        playGameService.endGame();

    }
}
