/*
 * This source file was generated by the Gradle 'init' task
 */
package org.TicTacToe;

import org.TicTacToe.Entities.Game;
import org.TicTacToe.Entities.ScoreBoard;
import org.TicTacToe.Services.InitializeGameService;
import org.TicTacToe.Services.UpdateScoreBoardService;

import java.util.ArrayList;
import java.util.List;

public class App {

    public static void main(String[] args) {

        ScoreBoard scoreBoard = new ScoreBoard();
        scoreBoard.setGames(new ArrayList<Game>());
        Game game1 = new InitializeGameService("Shanky", "Nigga", 3, 1).initializeGame();
        scoreBoard = new UpdateScoreBoardService().updateScoreBoard(scoreBoard, game1);

        



        System.out.println("\n");
    }
}
