/*
 * This source file was generated by the Gradle 'init' task
 */
package org.TicTacToe;

import org.TicTacToe.Entities.Game;
import org.TicTacToe.Entities.ScoreBoard;
import org.TicTacToe.Services.InitializeGameService;
import org.TicTacToe.Services.PlayGameService;
import org.TicTacToe.Services.PrintScoreBoardService;
import org.TicTacToe.Services.UpdateScoreBoardService;

import java.util.ArrayList;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        ScoreBoard scoreBoard = new ScoreBoard();
        scoreBoard.setGames(new ArrayList<Game>());
        Game game1 = new InitializeGameService("Shanky", "Nigga", 3, 1).initializeGame();
        scoreBoard = new UpdateScoreBoardService().updateScoreBoard(scoreBoard, game1);
        Scanner sc = new Scanner(System.in);
        game1 = new PlayGameService(game1, sc).playGame();
        scoreBoard = new UpdateScoreBoardService().updateScoreBoard(scoreBoard, game1);
        new PrintScoreBoardService().printScoreBoard(scoreBoard);
        System.out.println("\n");
    }

}
